mesh_file: package://swarm_visualization/meshes/test.stl
#mesh_file: package://swarm_visualization/meshes/mechanite_treads.stl

num_robots: 10
hit_radius: 0.20
warning_radius: 0.50
#cmd_time_out: 1.0

has_velocity_limiter: true
max_vx: 0.2
max_wz: 0.2
has_acceleration_limiter: false
max_acc_x: 1
max_acc_z: 1

x_0: 0
y_0: 0
x_1: 0
y_1: 0.19
x_2: 0
y_2: 0.59
x_3: 0
y_3: 1.5
x_4: 0.12
y_4: 0
x_5: 0.175
y_5: 0
x_6: 0.1457
y_6: 0
x_7: 0.145
y_7: 0.11
x_8: 0.1
y_8: 0.5454
x_9: 0.1
y_9: 0.54
x_10: 0.112157457
y_10: 0.12121